### ISSUE TITLE
PHPLint fails on PHP 8.0

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/actions#1]
PHPLint recently started giving issues, for example in the nightly build of Pronamic Pay:

https://github.com/pronamic/wp-pronamic-pay/actions/runs/7073661467

```
Unable to resolve action `overtrue/phplint@8.0`, unable to find version `8.0`
```

I tried to resolve the issue in https://github.com/pronamic/actions/compare/9873189…2da8f8f by updating to the suggested way to run PHPLint on the runtime PHP version (before, it was always running on the PHP version specified in the Dockerfile of the https://github.com/overtrue/phplint action — our matrix for PHP versions was useless):

https://github.com/overtrue/phplint/blob/fcd227df5fe62e87a22ef08e0fcbc927313a15f6/docs/usage/github-actions.md

> ## Use case 2
>
> Otherwise, if you want to detect specific PHP features used by scripts depending of your PHP runtime, then use this case.
>
> ```
>       ...
>
>       - name: Lint PHP files
>        run: |
>          curl -Ls https://github.com/overtrue/phplint/releases/latest/download/phplint.phar -o /usr/local/bin/phplint
>          chmod +x /usr/local/bin/phplint
>          /usr/local/bin/phplint -vvv --no-cache
> ```

However, the latest version ([9.0.6](https://github.com/overtrue/phplint/releases/tag/9.0.6)) requires PHP `>= 8.1`:

https://github.com/pronamic/wp-pronamic-pay/actions/runs/7189225432/job/19580366339

```
PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.30. in phar:///usr/local/bin/phplint/vendor/composer/platform_check.php on line 24
```

https://github.com/pronamic/actions/blob/main/.github/workflows/phplint.yml

According to https://github.com/overtrue/phplint/issues/181, the required PHP version `8.1` has to do with the way the PHPLint PHAR is created:

> This is the limit to use PHAR built on release https://github.com/overtrue/phplint/releases/tag/9.0.3
> Why: We use my project [box-manifest](https://github.com/llaville/box-manifest) to is the same as https://github.com/box-project/box v4 with a manifest (and BOX v4 min requirement is PHP 8.1)
> 
> If you want a PHAR that will run on PHP 8.0, we should compile it with BOX v3 ([3.16.0](https://github.com/box-project/box/tree/3.16.0))

**Comment by remcotolsma** [comment]
I see PHP 8.3 is released, we have the guideline to only support the latest 3 versions:

> We try to provide support for the last 3 major releases of PHP and WordPress in our projects.

https://github.com/pronamic/wp-coding-standards?tab=readme-ov-file#versions

Add PHP `8.3` and remove PHP `8.0`?

https://github.com/pronamic/actions/blob/e2eab61923efcca5a36b1b8d52dfbb99eef904c9/.github/workflows/phplint.yml#L12

**Comment by rvdsteege** [comment]
I've resolved the issue by downgrading our use of the https://github.com/overtrue/phplint action to version `4.5.0`, according to the PHP requirements in the readme (note that the PHAR for `9.x` actually requires PHP `>= 8.1`):

- https://github.com/pronamic/actions/commit/e2eab61923efcca5a36b1b8d52dfbb99eef904c9
- https://github.com/overtrue/phplint/blob/fcd227df5fe62e87a22ef08e0fcbc927313a15f6/README.md?plain=1#L13-L19

> | Version | Status                                    | Requirements   |
> |:--------|:------------------------------------------|:---------------|
> | **9.x** | **Active development**                    | **PHP >= 8.0** |
> | 6.x     | Active support                            | PHP >= 8.2     |
> | 5.x     | Active support                            | PHP >= 8.1     |
> | 4.x     | Active support                            | PHP >= 8.0     |
> | 3.x     | End Of Life                               | PHP >= 7.4     |

PHPLint is now working on PHP `8.0` again, for example in the Pronamic Pay nightly build:
- https://github.com/pronamic/wp-pronamic-pay/actions/runs/7193249985

However, I'm a bit uncomfortable with downgrading and I'm not sure if this is desired. What do you think, @remcotolsma?

**Comment by rvdsteege** [comment]
> Add PHP 8.3 and remove PHP 8.0?

Changed in https://github.com/pronamic/actions/commit/fe208492e952d5ef2346d26d2737a6327c2191d3 👍🏻

Pronamic Pay nightly build still working:
- https://github.com/pronamic/wp-pronamic-pay/actions/runs/7193374740
